sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hsujessie/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hsujessie/react-test npm test

after_success:
  - docker build -t j9686/multi-client ./client
  - docker build -t j9686/multi-nginx ./nginx
  - docker build -t j9686/multi-server ./server
  - docker build -t j9686/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push  j9686/multi-client
  - docker push  j9686/multi-nginx
  - docker push  j9686/multi-server
  - docker push  j9686/multi-worker